# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import ax_pb2 as proto_dot_ax__pb2


class AgentServiceStub(object):
    """AgentService defines the gRPC service for agent communication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Process = channel.stream_stream(
                '/proto.AgentService/Process',
                request_serializer=proto_dot_ax__pb2.ProcessRequest.SerializeToString,
                response_deserializer=proto_dot_ax__pb2.ProcessResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/proto.AgentService/HealthCheck',
                request_serializer=proto_dot_ax__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=proto_dot_ax__pb2.HealthCheckResponse.FromString,
                )


class AgentServiceServicer(object):
    """AgentService defines the gRPC service for agent communication
    """

    def Process(self, request_iterator, context):
        """Process handles bidirectional streaming of content between controller and agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """HealthCheck checks if the agent is healthy and responsive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Process': grpc.stream_stream_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=proto_dot_ax__pb2.ProcessRequest.FromString,
                    response_serializer=proto_dot_ax__pb2.ProcessResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_ax__pb2.HealthCheckRequest.FromString,
                    response_serializer=proto_dot_ax__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """AgentService defines the gRPC service for agent communication
    """

    @staticmethod
    def Process(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/proto.AgentService/Process',
            proto_dot_ax__pb2.ProcessRequest.SerializeToString,
            proto_dot_ax__pb2.ProcessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.AgentService/HealthCheck',
            proto_dot_ax__pb2.HealthCheckRequest.SerializeToString,
            proto_dot_ax__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class AXServiceStub(object):
    """AXService defines the gRPC service for AX operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Exec = channel.unary_stream(
                '/proto.AXService/Exec',
                request_serializer=proto_dot_ax__pb2.ExecRequest.SerializeToString,
                response_deserializer=proto_dot_ax__pb2.ExecResponse.FromString,
                )
        self.Fork = channel.unary_unary(
                '/proto.AXService/Fork',
                request_serializer=proto_dot_ax__pb2.ForkRequest.SerializeToString,
                response_deserializer=proto_dot_ax__pb2.ForkResponse.FromString,
                )
        self.RegisterAgent = channel.unary_unary(
                '/proto.AXService/RegisterAgent',
                request_serializer=proto_dot_ax__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=proto_dot_ax__pb2.RegisterAgentResponse.FromString,
                )


class AXServiceServicer(object):
    """AXService defines the gRPC service for AX operations
    """

    def Exec(self, request, context):
        """Exec executes an agentic task or resumes an existing one with streaming responses
        If the execution id already exists, it will be resumed from the last checkpoint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fork(self, request, context):
        """Fork forks an event log from a specific checkpoint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAgent(self, request, context):
        """RegisterAgent registers a new agent with the controller
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AXServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Exec': grpc.unary_stream_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=proto_dot_ax__pb2.ExecRequest.FromString,
                    response_serializer=proto_dot_ax__pb2.ExecResponse.SerializeToString,
            ),
            'Fork': grpc.unary_unary_rpc_method_handler(
                    servicer.Fork,
                    request_deserializer=proto_dot_ax__pb2.ForkRequest.FromString,
                    response_serializer=proto_dot_ax__pb2.ForkResponse.SerializeToString,
            ),
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=proto_dot_ax__pb2.RegisterAgentRequest.FromString,
                    response_serializer=proto_dot_ax__pb2.RegisterAgentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.AXService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AXService(object):
    """AXService defines the gRPC service for AX operations
    """

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/proto.AXService/Exec',
            proto_dot_ax__pb2.ExecRequest.SerializeToString,
            proto_dot_ax__pb2.ExecResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Fork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.AXService/Fork',
            proto_dot_ax__pb2.ForkRequest.SerializeToString,
            proto_dot_ax__pb2.ForkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.AXService/RegisterAgent',
            proto_dot_ax__pb2.RegisterAgentRequest.SerializeToString,
            proto_dot_ax__pb2.RegisterAgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
