// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: proto/content.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Resolution for input media (images/video).
type MediaResolution int32

const (
	MediaResolution_MEDIA_RESOLUTION_UNSPECIFIED MediaResolution = 0
	MediaResolution_LOW                          MediaResolution = 1
	MediaResolution_MEDIUM                       MediaResolution = 2
	MediaResolution_HIGH                         MediaResolution = 3
	MediaResolution_ULTRA_HIGH                   MediaResolution = 4
)

// Enum value maps for MediaResolution.
var (
	MediaResolution_name = map[int32]string{
		0: "MEDIA_RESOLUTION_UNSPECIFIED",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
		4: "ULTRA_HIGH",
	}
	MediaResolution_value = map[string]int32{
		"MEDIA_RESOLUTION_UNSPECIFIED": 0,
		"LOW":                          1,
		"MEDIUM":                       2,
		"HIGH":                         3,
		"ULTRA_HIGH":                   4,
	}
)

func (x MediaResolution) Enum() *MediaResolution {
	p := new(MediaResolution)
	*p = x
	return p
}

func (x MediaResolution) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaResolution) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_content_proto_enumTypes[0].Descriptor()
}

func (MediaResolution) Type() protoreflect.EnumType {
	return &file_proto_content_proto_enumTypes[0]
}

func (x MediaResolution) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaResolution.Descriptor instead.
func (MediaResolution) EnumDescriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{0}
}

type ImageContent_MimeType int32

const (
	ImageContent_TYPE_UNSPECIFIED ImageContent_MimeType = 0
	ImageContent_TYPE_PNG         ImageContent_MimeType = 1 // image/png
	ImageContent_TYPE_JPEG        ImageContent_MimeType = 2 // image/jpeg
	ImageContent_TYPE_WEBP        ImageContent_MimeType = 3 // image/webp
	ImageContent_TYPE_HEIC        ImageContent_MimeType = 4 // image/heic
	ImageContent_TYPE_HEIF        ImageContent_MimeType = 5 // image/heif
	ImageContent_TYPE_GIF         ImageContent_MimeType = 7 // image/gif
	ImageContent_TYPE_BMP         ImageContent_MimeType = 8 // image/bmp
	ImageContent_TYPE_TIFF        ImageContent_MimeType = 9 // image/tiff
)

// Enum value maps for ImageContent_MimeType.
var (
	ImageContent_MimeType_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_PNG",
		2: "TYPE_JPEG",
		3: "TYPE_WEBP",
		4: "TYPE_HEIC",
		5: "TYPE_HEIF",
		7: "TYPE_GIF",
		8: "TYPE_BMP",
		9: "TYPE_TIFF",
	}
	ImageContent_MimeType_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_PNG":         1,
		"TYPE_JPEG":        2,
		"TYPE_WEBP":        3,
		"TYPE_HEIC":        4,
		"TYPE_HEIF":        5,
		"TYPE_GIF":         7,
		"TYPE_BMP":         8,
		"TYPE_TIFF":        9,
	}
)

func (x ImageContent_MimeType) Enum() *ImageContent_MimeType {
	p := new(ImageContent_MimeType)
	*p = x
	return p
}

func (x ImageContent_MimeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageContent_MimeType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_content_proto_enumTypes[1].Descriptor()
}

func (ImageContent_MimeType) Type() protoreflect.EnumType {
	return &file_proto_content_proto_enumTypes[1]
}

func (x ImageContent_MimeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageContent_MimeType.Descriptor instead.
func (ImageContent_MimeType) EnumDescriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{10, 0}
}

type AudioContent_MimeType int32

const (
	AudioContent_TYPE_UNSPECIFIED AudioContent_MimeType = 0
	AudioContent_TYPE_WAV         AudioContent_MimeType = 1  // audio/wav
	AudioContent_TYPE_MP3         AudioContent_MimeType = 2  // audio/mp3
	AudioContent_TYPE_AIFF        AudioContent_MimeType = 3  // audio/aiff
	AudioContent_TYPE_AAC         AudioContent_MimeType = 4  // audio/aac
	AudioContent_TYPE_OGG         AudioContent_MimeType = 5  // audio/ogg
	AudioContent_TYPE_FLAC        AudioContent_MimeType = 6  // audio/flac
	AudioContent_TYPE_MPEG        AudioContent_MimeType = 7  // audio/mpeg
	AudioContent_TYPE_M4A         AudioContent_MimeType = 8  // audio/m4a
	AudioContent_TYPE_L16         AudioContent_MimeType = 9  // audio/l16
	AudioContent_TYPE_S16LE       AudioContent_MimeType = 10 // audio/s16le
	AudioContent_TYPE_OPUS        AudioContent_MimeType = 11 // audio/opus
	AudioContent_TYPE_ALAW        AudioContent_MimeType = 12 // audio/alaw
	AudioContent_TYPE_MULAW       AudioContent_MimeType = 13 // audio/mulaw
)

// Enum value maps for AudioContent_MimeType.
var (
	AudioContent_MimeType_name = map[int32]string{
		0:  "TYPE_UNSPECIFIED",
		1:  "TYPE_WAV",
		2:  "TYPE_MP3",
		3:  "TYPE_AIFF",
		4:  "TYPE_AAC",
		5:  "TYPE_OGG",
		6:  "TYPE_FLAC",
		7:  "TYPE_MPEG",
		8:  "TYPE_M4A",
		9:  "TYPE_L16",
		10: "TYPE_S16LE",
		11: "TYPE_OPUS",
		12: "TYPE_ALAW",
		13: "TYPE_MULAW",
	}
	AudioContent_MimeType_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_WAV":         1,
		"TYPE_MP3":         2,
		"TYPE_AIFF":        3,
		"TYPE_AAC":         4,
		"TYPE_OGG":         5,
		"TYPE_FLAC":        6,
		"TYPE_MPEG":        7,
		"TYPE_M4A":         8,
		"TYPE_L16":         9,
		"TYPE_S16LE":       10,
		"TYPE_OPUS":        11,
		"TYPE_ALAW":        12,
		"TYPE_MULAW":       13,
	}
)

func (x AudioContent_MimeType) Enum() *AudioContent_MimeType {
	p := new(AudioContent_MimeType)
	*p = x
	return p
}

func (x AudioContent_MimeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioContent_MimeType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_content_proto_enumTypes[2].Descriptor()
}

func (AudioContent_MimeType) Type() protoreflect.EnumType {
	return &file_proto_content_proto_enumTypes[2]
}

func (x AudioContent_MimeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioContent_MimeType.Descriptor instead.
func (AudioContent_MimeType) EnumDescriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{11, 0}
}

type DocumentContent_MimeType int32

const (
	DocumentContent_TYPE_UNSPECIFIED DocumentContent_MimeType = 0
	DocumentContent_TYPE_PDF         DocumentContent_MimeType = 1 // application/pdf
	DocumentContent_TYPE_JSON        DocumentContent_MimeType = 2 // application/json
	DocumentContent_TYPE_PYTHON      DocumentContent_MimeType = 3 // text/x-python
)

// Enum value maps for DocumentContent_MimeType.
var (
	DocumentContent_MimeType_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_PDF",
		2: "TYPE_JSON",
		3: "TYPE_PYTHON",
	}
	DocumentContent_MimeType_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_PDF":         1,
		"TYPE_JSON":        2,
		"TYPE_PYTHON":      3,
	}
)

func (x DocumentContent_MimeType) Enum() *DocumentContent_MimeType {
	p := new(DocumentContent_MimeType)
	*p = x
	return p
}

func (x DocumentContent_MimeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentContent_MimeType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_content_proto_enumTypes[3].Descriptor()
}

func (DocumentContent_MimeType) Type() protoreflect.EnumType {
	return &file_proto_content_proto_enumTypes[3]
}

func (x DocumentContent_MimeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentContent_MimeType.Descriptor instead.
func (DocumentContent_MimeType) EnumDescriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{12, 0}
}

type VideoContent_MimeType int32

const (
	VideoContent_TYPE_UNSPECIFIED VideoContent_MimeType = 0
	VideoContent_TYPE_MP4         VideoContent_MimeType = 1 // video/mp4
	VideoContent_TYPE_MPEG        VideoContent_MimeType = 2 // video/mpeg
	VideoContent_TYPE_MPG         VideoContent_MimeType = 3 // video/mpg
	VideoContent_TYPE_MOV         VideoContent_MimeType = 4 // video/mov
	VideoContent_TYPE_AVI         VideoContent_MimeType = 5 // video/avi
	VideoContent_TYPE_X_FLV       VideoContent_MimeType = 6 // video/x-flv
	VideoContent_TYPE_WEBM        VideoContent_MimeType = 7 // video/webm
	VideoContent_TYPE_WMV         VideoContent_MimeType = 8 // video/wmv
	VideoContent_TYPE_3GPP        VideoContent_MimeType = 9 // video/3gpp
)

// Enum value maps for VideoContent_MimeType.
var (
	VideoContent_MimeType_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_MP4",
		2: "TYPE_MPEG",
		3: "TYPE_MPG",
		4: "TYPE_MOV",
		5: "TYPE_AVI",
		6: "TYPE_X_FLV",
		7: "TYPE_WEBM",
		8: "TYPE_WMV",
		9: "TYPE_3GPP",
	}
	VideoContent_MimeType_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_MP4":         1,
		"TYPE_MPEG":        2,
		"TYPE_MPG":         3,
		"TYPE_MOV":         4,
		"TYPE_AVI":         5,
		"TYPE_X_FLV":       6,
		"TYPE_WEBM":        7,
		"TYPE_WMV":         8,
		"TYPE_3GPP":        9,
	}
)

func (x VideoContent_MimeType) Enum() *VideoContent_MimeType {
	p := new(VideoContent_MimeType)
	*p = x
	return p
}

func (x VideoContent_MimeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoContent_MimeType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_content_proto_enumTypes[4].Descriptor()
}

func (VideoContent_MimeType) Type() protoreflect.EnumType {
	return &file_proto_content_proto_enumTypes[4]
}

func (x VideoContent_MimeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoContent_MimeType.Descriptor instead.
func (VideoContent_MimeType) EnumDescriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{13, 0}
}

// TextContent represents a text content.
type TextContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextContent) Reset() {
	*x = TextContent{}
	mi := &file_proto_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextContent) ProtoMessage() {}

func (x *TextContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextContent.ProtoReflect.Descriptor instead.
func (*TextContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{0}
}

func (x *TextContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ApprovalDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalDecision) Reset() {
	*x = ApprovalDecision{}
	mi := &file_proto_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalDecision) ProtoMessage() {}

func (x *ApprovalDecision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalDecision.ProtoReflect.Descriptor instead.
func (*ApprovalDecision) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{1}
}

func (x *ApprovalDecision) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type DeclineDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Declined      bool                   `protobuf:"varint,1,opt,name=declined,proto3" json:"declined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineDecision) Reset() {
	*x = DeclineDecision{}
	mi := &file_proto_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineDecision) ProtoMessage() {}

func (x *DeclineDecision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineDecision.ProtoReflect.Descriptor instead.
func (*DeclineDecision) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{2}
}

func (x *DeclineDecision) GetDeclined() bool {
	if x != nil {
		return x.Declined
	}
	return false
}

type ConfirmationContent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Question string                 `protobuf:"bytes,4,opt,name=question,proto3" json:"question,omitempty"`
	// Types that are valid to be assigned to Decision:
	//
	//	*ConfirmationContent_Approval
	//	*ConfirmationContent_Decline
	Decision      isConfirmationContent_Decision `protobuf_oneof:"decision"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmationContent) Reset() {
	*x = ConfirmationContent{}
	mi := &file_proto_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmationContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmationContent) ProtoMessage() {}

func (x *ConfirmationContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmationContent.ProtoReflect.Descriptor instead.
func (*ConfirmationContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmationContent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfirmationContent) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *ConfirmationContent) GetDecision() isConfirmationContent_Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}

func (x *ConfirmationContent) GetApproval() *ApprovalDecision {
	if x != nil {
		if x, ok := x.Decision.(*ConfirmationContent_Approval); ok {
			return x.Approval
		}
	}
	return nil
}

func (x *ConfirmationContent) GetDecline() *DeclineDecision {
	if x != nil {
		if x, ok := x.Decision.(*ConfirmationContent_Decline); ok {
			return x.Decline
		}
	}
	return nil
}

type isConfirmationContent_Decision interface {
	isConfirmationContent_Decision()
}

type ConfirmationContent_Approval struct {
	Approval *ApprovalDecision `protobuf:"bytes,5,opt,name=approval,proto3,oneof"`
}

type ConfirmationContent_Decline struct {
	Decline *DeclineDecision `protobuf:"bytes,6,opt,name=decline,proto3,oneof"`
}

func (*ConfirmationContent_Approval) isConfirmationContent_Decision() {}

func (*ConfirmationContent_Decline) isConfirmationContent_Decision() {}

type ThoughtSummaryContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*ThoughtSummaryContent_Text
	Type          isThoughtSummaryContent_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThoughtSummaryContent) Reset() {
	*x = ThoughtSummaryContent{}
	mi := &file_proto_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThoughtSummaryContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThoughtSummaryContent) ProtoMessage() {}

func (x *ThoughtSummaryContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThoughtSummaryContent.ProtoReflect.Descriptor instead.
func (*ThoughtSummaryContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{4}
}

func (x *ThoughtSummaryContent) GetType() isThoughtSummaryContent_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ThoughtSummaryContent) GetText() *TextContent {
	if x != nil {
		if x, ok := x.Type.(*ThoughtSummaryContent_Text); ok {
			return x.Text
		}
	}
	return nil
}

type isThoughtSummaryContent_Type interface {
	isThoughtSummaryContent_Type()
}

type ThoughtSummaryContent_Text struct {
	Text *TextContent `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

func (*ThoughtSummaryContent_Text) isThoughtSummaryContent_Type() {}

type ThoughtContent struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Signature     []byte                   `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	Summary       []*ThoughtSummaryContent `protobuf:"bytes,9,rep,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThoughtContent) Reset() {
	*x = ThoughtContent{}
	mi := &file_proto_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThoughtContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThoughtContent) ProtoMessage() {}

func (x *ThoughtContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThoughtContent.ProtoReflect.Descriptor instead.
func (*ThoughtContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{5}
}

func (x *ThoughtContent) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ThoughtContent) GetSummary() []*ThoughtSummaryContent {
	if x != nil {
		return x.Summary
	}
	return nil
}

type ToolCallContent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`               // A unique ID for this specific tool call.
	Signature []byte                 `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"` // A signature hash for backend validation.
	// Types that are valid to be assigned to Type:
	//
	//	*ToolCallContent_FunctionCall
	Type          isToolCallContent_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallContent) Reset() {
	*x = ToolCallContent{}
	mi := &file_proto_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallContent) ProtoMessage() {}

func (x *ToolCallContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallContent.ProtoReflect.Descriptor instead.
func (*ToolCallContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{6}
}

func (x *ToolCallContent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCallContent) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ToolCallContent) GetType() isToolCallContent_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ToolCallContent) GetFunctionCall() *FunctionCallContent {
	if x != nil {
		if x, ok := x.Type.(*ToolCallContent_FunctionCall); ok {
			return x.FunctionCall
		}
	}
	return nil
}

type isToolCallContent_Type interface {
	isToolCallContent_Type()
}

type ToolCallContent_FunctionCall struct {
	FunctionCall *FunctionCallContent `protobuf:"bytes,2,opt,name=function_call,json=functionCall,proto3,oneof"`
}

func (*ToolCallContent_FunctionCall) isToolCallContent_Type() {}

type ToolResultContent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CallId    string                 `protobuf:"bytes,8,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"` // ID to match the ID from the function call block.
	Signature []byte                 `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`         // A signature hash for backend validation.
	// Types that are valid to be assigned to Type:
	//
	//	*ToolResultContent_FunctionResult
	Type          isToolResultContent_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResultContent) Reset() {
	*x = ToolResultContent{}
	mi := &file_proto_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultContent) ProtoMessage() {}

func (x *ToolResultContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResultContent.ProtoReflect.Descriptor instead.
func (*ToolResultContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{7}
}

func (x *ToolResultContent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolResultContent) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ToolResultContent) GetType() isToolResultContent_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ToolResultContent) GetFunctionResult() *FunctionResultContent {
	if x != nil {
		if x, ok := x.Type.(*ToolResultContent_FunctionResult); ok {
			return x.FunctionResult
		}
	}
	return nil
}

type isToolResultContent_Type interface {
	isToolResultContent_Type()
}

type ToolResultContent_FunctionResult struct {
	FunctionResult *FunctionResultContent `protobuf:"bytes,2,opt,name=function_result,json=functionResult,proto3,oneof"`
}

func (*ToolResultContent_FunctionResult) isToolResultContent_Type() {}

type FunctionCallContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     *structpb.Struct       `protobuf:"bytes,4,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionCallContent) Reset() {
	*x = FunctionCallContent{}
	mi := &file_proto_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCallContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCallContent) ProtoMessage() {}

func (x *FunctionCallContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCallContent.ProtoReflect.Descriptor instead.
func (*FunctionCallContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{8}
}

func (x *FunctionCallContent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionCallContent) GetArguments() *structpb.Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type FunctionResultContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*FunctionResultContent_Response
	Result        isFunctionResultContent_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionResultContent) Reset() {
	*x = FunctionResultContent{}
	mi := &file_proto_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionResultContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionResultContent) ProtoMessage() {}

func (x *FunctionResultContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionResultContent.ProtoReflect.Descriptor instead.
func (*FunctionResultContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{9}
}

func (x *FunctionResultContent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionResultContent) GetResult() isFunctionResultContent_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *FunctionResultContent) GetResponse() *structpb.Struct {
	if x != nil {
		if x, ok := x.Result.(*FunctionResultContent_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isFunctionResultContent_Result interface {
	isFunctionResultContent_Result()
}

type FunctionResultContent_Response struct {
	Response *structpb.Struct `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

func (*FunctionResultContent_Response) isFunctionResultContent_Result() {}

// An image content block.
type ImageContent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	MimeType ImageContent_MimeType  `protobuf:"varint,1,opt,name=mime_type,json=mimeType,proto3,enum=ax.ImageContent_MimeType" json:"mime_type,omitempty"`
	// Types that are valid to be assigned to DataOrUri:
	//
	//	*ImageContent_Data
	//	*ImageContent_Uri
	DataOrUri     isImageContent_DataOrUri `protobuf_oneof:"data_or_uri"`
	Resolution    MediaResolution          `protobuf:"varint,5,opt,name=resolution,proto3,enum=ax.MediaResolution" json:"resolution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageContent) Reset() {
	*x = ImageContent{}
	mi := &file_proto_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageContent) ProtoMessage() {}

func (x *ImageContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageContent.ProtoReflect.Descriptor instead.
func (*ImageContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{10}
}

func (x *ImageContent) GetMimeType() ImageContent_MimeType {
	if x != nil {
		return x.MimeType
	}
	return ImageContent_TYPE_UNSPECIFIED
}

func (x *ImageContent) GetDataOrUri() isImageContent_DataOrUri {
	if x != nil {
		return x.DataOrUri
	}
	return nil
}

func (x *ImageContent) GetData() []byte {
	if x != nil {
		if x, ok := x.DataOrUri.(*ImageContent_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *ImageContent) GetUri() string {
	if x != nil {
		if x, ok := x.DataOrUri.(*ImageContent_Uri); ok {
			return x.Uri
		}
	}
	return ""
}

func (x *ImageContent) GetResolution() MediaResolution {
	if x != nil {
		return x.Resolution
	}
	return MediaResolution_MEDIA_RESOLUTION_UNSPECIFIED
}

type isImageContent_DataOrUri interface {
	isImageContent_DataOrUri()
}

type ImageContent_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type ImageContent_Uri struct {
	Uri string `protobuf:"bytes,6,opt,name=uri,proto3,oneof"`
}

func (*ImageContent_Data) isImageContent_DataOrUri() {}

func (*ImageContent_Uri) isImageContent_DataOrUri() {}

// An audio content block.
type AudioContent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	MimeType AudioContent_MimeType  `protobuf:"varint,1,opt,name=mime_type,json=mimeType,proto3,enum=ax.AudioContent_MimeType" json:"mime_type,omitempty"`
	// Types that are valid to be assigned to DataOrUri:
	//
	//	*AudioContent_Data
	//	*AudioContent_Uri
	DataOrUri     isAudioContent_DataOrUri `protobuf_oneof:"data_or_uri"`
	Channels      int32                    `protobuf:"varint,7,opt,name=channels,proto3" json:"channels,omitempty"`
	SampleRate    int32                    `protobuf:"varint,8,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioContent) Reset() {
	*x = AudioContent{}
	mi := &file_proto_content_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioContent) ProtoMessage() {}

func (x *AudioContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioContent.ProtoReflect.Descriptor instead.
func (*AudioContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{11}
}

func (x *AudioContent) GetMimeType() AudioContent_MimeType {
	if x != nil {
		return x.MimeType
	}
	return AudioContent_TYPE_UNSPECIFIED
}

func (x *AudioContent) GetDataOrUri() isAudioContent_DataOrUri {
	if x != nil {
		return x.DataOrUri
	}
	return nil
}

func (x *AudioContent) GetData() []byte {
	if x != nil {
		if x, ok := x.DataOrUri.(*AudioContent_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *AudioContent) GetUri() string {
	if x != nil {
		if x, ok := x.DataOrUri.(*AudioContent_Uri); ok {
			return x.Uri
		}
	}
	return ""
}

func (x *AudioContent) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *AudioContent) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type isAudioContent_DataOrUri interface {
	isAudioContent_DataOrUri()
}

type AudioContent_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type AudioContent_Uri struct {
	Uri string `protobuf:"bytes,5,opt,name=uri,proto3,oneof"`
}

func (*AudioContent_Data) isAudioContent_DataOrUri() {}

func (*AudioContent_Uri) isAudioContent_DataOrUri() {}

// A document content block.
type DocumentContent struct {
	state    protoimpl.MessageState   `protogen:"open.v1"`
	MimeType DocumentContent_MimeType `protobuf:"varint,1,opt,name=mime_type,json=mimeType,proto3,enum=ax.DocumentContent_MimeType" json:"mime_type,omitempty"`
	// Types that are valid to be assigned to DataOrUri:
	//
	//	*DocumentContent_Data
	//	*DocumentContent_Uri
	DataOrUri     isDocumentContent_DataOrUri `protobuf_oneof:"data_or_uri"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentContent) Reset() {
	*x = DocumentContent{}
	mi := &file_proto_content_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentContent) ProtoMessage() {}

func (x *DocumentContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentContent.ProtoReflect.Descriptor instead.
func (*DocumentContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{12}
}

func (x *DocumentContent) GetMimeType() DocumentContent_MimeType {
	if x != nil {
		return x.MimeType
	}
	return DocumentContent_TYPE_UNSPECIFIED
}

func (x *DocumentContent) GetDataOrUri() isDocumentContent_DataOrUri {
	if x != nil {
		return x.DataOrUri
	}
	return nil
}

func (x *DocumentContent) GetData() []byte {
	if x != nil {
		if x, ok := x.DataOrUri.(*DocumentContent_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *DocumentContent) GetUri() string {
	if x != nil {
		if x, ok := x.DataOrUri.(*DocumentContent_Uri); ok {
			return x.Uri
		}
	}
	return ""
}

type isDocumentContent_DataOrUri interface {
	isDocumentContent_DataOrUri()
}

type DocumentContent_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type DocumentContent_Uri struct {
	Uri string `protobuf:"bytes,5,opt,name=uri,proto3,oneof"`
}

func (*DocumentContent_Data) isDocumentContent_DataOrUri() {}

func (*DocumentContent_Uri) isDocumentContent_DataOrUri() {}

// A video content block.
type VideoContent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	MimeType VideoContent_MimeType  `protobuf:"varint,1,opt,name=mime_type,json=mimeType,proto3,enum=ax.VideoContent_MimeType" json:"mime_type,omitempty"`
	// Types that are valid to be assigned to DataOrUri:
	//
	//	*VideoContent_Data
	//	*VideoContent_Uri
	DataOrUri     isVideoContent_DataOrUri `protobuf_oneof:"data_or_uri"`
	Resolution    MediaResolution          `protobuf:"varint,5,opt,name=resolution,proto3,enum=ax.MediaResolution" json:"resolution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoContent) Reset() {
	*x = VideoContent{}
	mi := &file_proto_content_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoContent) ProtoMessage() {}

func (x *VideoContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoContent.ProtoReflect.Descriptor instead.
func (*VideoContent) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{13}
}

func (x *VideoContent) GetMimeType() VideoContent_MimeType {
	if x != nil {
		return x.MimeType
	}
	return VideoContent_TYPE_UNSPECIFIED
}

func (x *VideoContent) GetDataOrUri() isVideoContent_DataOrUri {
	if x != nil {
		return x.DataOrUri
	}
	return nil
}

func (x *VideoContent) GetData() []byte {
	if x != nil {
		if x, ok := x.DataOrUri.(*VideoContent_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *VideoContent) GetUri() string {
	if x != nil {
		if x, ok := x.DataOrUri.(*VideoContent_Uri); ok {
			return x.Uri
		}
	}
	return ""
}

func (x *VideoContent) GetResolution() MediaResolution {
	if x != nil {
		return x.Resolution
	}
	return MediaResolution_MEDIA_RESOLUTION_UNSPECIFIED
}

type isVideoContent_DataOrUri interface {
	isVideoContent_DataOrUri()
}

type VideoContent_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type VideoContent_Uri struct {
	Uri string `protobuf:"bytes,6,opt,name=uri,proto3,oneof"`
}

func (*VideoContent_Data) isVideoContent_DataOrUri() {}

func (*VideoContent_Uri) isVideoContent_DataOrUri() {}

// Content represents a content input or output.
type Content struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*Content_Thought
	//	*Content_Text
	//	*Content_Image
	//	*Content_Audio
	//	*Content_Document
	//	*Content_Video
	//	*Content_Confirmation
	//	*Content_ToolCall
	//	*Content_ToolResult
	Type          isContent_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_proto_content_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_proto_content_proto_rawDescGZIP(), []int{14}
}

func (x *Content) GetType() isContent_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Content) GetThought() *ThoughtContent {
	if x != nil {
		if x, ok := x.Type.(*Content_Thought); ok {
			return x.Thought
		}
	}
	return nil
}

func (x *Content) GetText() *TextContent {
	if x != nil {
		if x, ok := x.Type.(*Content_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *Content) GetImage() *ImageContent {
	if x != nil {
		if x, ok := x.Type.(*Content_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *Content) GetAudio() *AudioContent {
	if x != nil {
		if x, ok := x.Type.(*Content_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *Content) GetDocument() *DocumentContent {
	if x != nil {
		if x, ok := x.Type.(*Content_Document); ok {
			return x.Document
		}
	}
	return nil
}

func (x *Content) GetVideo() *VideoContent {
	if x != nil {
		if x, ok := x.Type.(*Content_Video); ok {
			return x.Video
		}
	}
	return nil
}

func (x *Content) GetConfirmation() *ConfirmationContent {
	if x != nil {
		if x, ok := x.Type.(*Content_Confirmation); ok {
			return x.Confirmation
		}
	}
	return nil
}

func (x *Content) GetToolCall() *ToolCallContent {
	if x != nil {
		if x, ok := x.Type.(*Content_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *Content) GetToolResult() *ToolResultContent {
	if x != nil {
		if x, ok := x.Type.(*Content_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

type isContent_Type interface {
	isContent_Type()
}

type Content_Thought struct {
	Thought *ThoughtContent `protobuf:"bytes,5,opt,name=thought,proto3,oneof"`
}

type Content_Text struct {
	Text *TextContent `protobuf:"bytes,10,opt,name=text,proto3,oneof"`
}

type Content_Image struct {
	Image *ImageContent `protobuf:"bytes,11,opt,name=image,proto3,oneof"`
}

type Content_Audio struct {
	Audio *AudioContent `protobuf:"bytes,12,opt,name=audio,proto3,oneof"`
}

type Content_Document struct {
	Document *DocumentContent `protobuf:"bytes,13,opt,name=document,proto3,oneof"`
}

type Content_Video struct {
	Video *VideoContent `protobuf:"bytes,14,opt,name=video,proto3,oneof"`
}

type Content_Confirmation struct {
	Confirmation *ConfirmationContent `protobuf:"bytes,26,opt,name=confirmation,proto3,oneof"` // TODO(jbd): Remove out of the Content.
}

type Content_ToolCall struct {
	ToolCall *ToolCallContent `protobuf:"bytes,24,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

type Content_ToolResult struct {
	ToolResult *ToolResultContent `protobuf:"bytes,25,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

func (*Content_Thought) isContent_Type() {}

func (*Content_Text) isContent_Type() {}

func (*Content_Image) isContent_Type() {}

func (*Content_Audio) isContent_Type() {}

func (*Content_Document) isContent_Type() {}

func (*Content_Video) isContent_Type() {}

func (*Content_Confirmation) isContent_Type() {}

func (*Content_ToolCall) isContent_Type() {}

func (*Content_ToolResult) isContent_Type() {}

var File_proto_content_proto protoreflect.FileDescriptor

const file_proto_content_proto_rawDesc = "" +
	"\n" +
	"\x13proto/content.proto\x12\x02ax\x1a\x1cgoogle/protobuf/struct.proto\"3\n" +
	"\vTextContent\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04textJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03R\x04type\".\n" +
	"\x10ApprovalDecision\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\";\n" +
	"\x0fDeclineDecision\x12\x1a\n" +
	"\bdeclined\x18\x01 \x01(\bR\bdeclinedJ\x04\b\x02\x10\x03R\x06reason\"\xc4\x01\n" +
	"\x13ConfirmationContent\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1a\n" +
	"\bquestion\x18\x04 \x01(\tR\bquestion\x122\n" +
	"\bapproval\x18\x05 \x01(\v2\x14.ax.ApprovalDecisionH\x00R\bapproval\x12/\n" +
	"\adecline\x18\x06 \x01(\v2\x13.ax.DeclineDecisionH\x00R\adeclineB\n" +
	"\n" +
	"\bdecisionJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03R\x04type\"L\n" +
	"\x15ThoughtSummaryContent\x12%\n" +
	"\x04text\x18\x01 \x01(\v2\x0f.ax.TextContentH\x00R\x04textB\x06\n" +
	"\x04typeJ\x04\b\x02\x10\x03\"\x8d\x01\n" +
	"\x0eThoughtContent\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\x123\n" +
	"\asummary\x18\t \x03(\v2\x19.ax.ThoughtSummaryContentR\asummaryJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\b\x10\tR\x04type\"\x87\x01\n" +
	"\x0fToolCallContent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tsignature\x18\t \x01(\fR\tsignature\x12>\n" +
	"\rfunction_call\x18\x02 \x01(\v2\x17.ax.FunctionCallContentH\x00R\ffunctionCallB\x06\n" +
	"\x04type\"\x9e\x01\n" +
	"\x11ToolResultContent\x12\x17\n" +
	"\acall_id\x18\b \x01(\tR\x06callId\x12\x1c\n" +
	"\tsignature\x18\t \x01(\fR\tsignature\x12D\n" +
	"\x0ffunction_result\x18\x02 \x01(\v2\x19.ax.FunctionResultContentH\x00R\x0efunctionResultB\x06\n" +
	"\x04typeJ\x04\b\x01\x10\x02\"l\n" +
	"\x13FunctionCallContent\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x125\n" +
	"\targuments\x18\x04 \x01(\v2\x17.google.protobuf.StructR\targumentsJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03\"~\n" +
	"\x15FunctionResultContent\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x125\n" +
	"\bresponse\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x00R\bresponseB\b\n" +
	"\x06resultJ\x04\b\x01\x10\x02J\x04\b\x04\x10\x05R\x04type\"\xde\x02\n" +
	"\fImageContent\x126\n" +
	"\tmime_type\x18\x01 \x01(\x0e2\x19.ax.ImageContent.MimeTypeR\bmimeType\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x12\x12\n" +
	"\x03uri\x18\x06 \x01(\tH\x00R\x03uri\x123\n" +
	"\n" +
	"resolution\x18\x05 \x01(\x0e2\x13.ax.MediaResolutionR\n" +
	"resolution\"\x9b\x01\n" +
	"\bMimeType\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bTYPE_PNG\x10\x01\x12\r\n" +
	"\tTYPE_JPEG\x10\x02\x12\r\n" +
	"\tTYPE_WEBP\x10\x03\x12\r\n" +
	"\tTYPE_HEIC\x10\x04\x12\r\n" +
	"\tTYPE_HEIF\x10\x05\x12\f\n" +
	"\bTYPE_GIF\x10\a\x12\f\n" +
	"\bTYPE_BMP\x10\b\x12\r\n" +
	"\tTYPE_TIFF\x10\t\"\x04\b\x06\x10\x06B\r\n" +
	"\vdata_or_uriJ\x04\b\x03\x10\x04R\x04type\"\xb6\x03\n" +
	"\fAudioContent\x126\n" +
	"\tmime_type\x18\x01 \x01(\x0e2\x19.ax.AudioContent.MimeTypeR\bmimeType\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x12\x12\n" +
	"\x03uri\x18\x05 \x01(\tH\x00R\x03uri\x12\x1a\n" +
	"\bchannels\x18\a \x01(\x05R\bchannels\x12\x1f\n" +
	"\vsample_rate\x18\b \x01(\x05R\n" +
	"sampleRate\"\xdf\x01\n" +
	"\bMimeType\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bTYPE_WAV\x10\x01\x12\f\n" +
	"\bTYPE_MP3\x10\x02\x12\r\n" +
	"\tTYPE_AIFF\x10\x03\x12\f\n" +
	"\bTYPE_AAC\x10\x04\x12\f\n" +
	"\bTYPE_OGG\x10\x05\x12\r\n" +
	"\tTYPE_FLAC\x10\x06\x12\r\n" +
	"\tTYPE_MPEG\x10\a\x12\f\n" +
	"\bTYPE_M4A\x10\b\x12\f\n" +
	"\bTYPE_L16\x10\t\x12\x0e\n" +
	"\n" +
	"TYPE_S16LE\x10\n" +
	"\x12\r\n" +
	"\tTYPE_OPUS\x10\v\x12\r\n" +
	"\tTYPE_ALAW\x10\f\x12\x0e\n" +
	"\n" +
	"TYPE_MULAW\x10\rB\r\n" +
	"\vdata_or_uriJ\x04\b\x03\x10\x04J\x04\b\x06\x10\aR\x04typeR\x04rate\"\xe1\x01\n" +
	"\x0fDocumentContent\x129\n" +
	"\tmime_type\x18\x01 \x01(\x0e2\x1c.ax.DocumentContent.MimeTypeR\bmimeType\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x12\x12\n" +
	"\x03uri\x18\x05 \x01(\tH\x00R\x03uri\"N\n" +
	"\bMimeType\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bTYPE_PDF\x10\x01\x12\r\n" +
	"\tTYPE_JSON\x10\x02\x12\x0f\n" +
	"\vTYPE_PYTHON\x10\x03B\r\n" +
	"\vdata_or_uriJ\x04\b\x03\x10\x04R\x04type\"\xe6\x02\n" +
	"\fVideoContent\x126\n" +
	"\tmime_type\x18\x01 \x01(\x0e2\x19.ax.VideoContent.MimeTypeR\bmimeType\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x12\x12\n" +
	"\x03uri\x18\x06 \x01(\tH\x00R\x03uri\x123\n" +
	"\n" +
	"resolution\x18\x05 \x01(\x0e2\x13.ax.MediaResolutionR\n" +
	"resolution\"\xa3\x01\n" +
	"\bMimeType\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bTYPE_MP4\x10\x01\x12\r\n" +
	"\tTYPE_MPEG\x10\x02\x12\f\n" +
	"\bTYPE_MPG\x10\x03\x12\f\n" +
	"\bTYPE_MOV\x10\x04\x12\f\n" +
	"\bTYPE_AVI\x10\x05\x12\x0e\n" +
	"\n" +
	"TYPE_X_FLV\x10\x06\x12\r\n" +
	"\tTYPE_WEBM\x10\a\x12\f\n" +
	"\bTYPE_WMV\x10\b\x12\r\n" +
	"\tTYPE_3GPP\x10\tB\r\n" +
	"\vdata_or_uriJ\x04\b\x03\x10\x04R\x04type\"\xd8\x03\n" +
	"\aContent\x12.\n" +
	"\athought\x18\x05 \x01(\v2\x12.ax.ThoughtContentH\x00R\athought\x12%\n" +
	"\x04text\x18\n" +
	" \x01(\v2\x0f.ax.TextContentH\x00R\x04text\x12(\n" +
	"\x05image\x18\v \x01(\v2\x10.ax.ImageContentH\x00R\x05image\x12(\n" +
	"\x05audio\x18\f \x01(\v2\x10.ax.AudioContentH\x00R\x05audio\x121\n" +
	"\bdocument\x18\r \x01(\v2\x13.ax.DocumentContentH\x00R\bdocument\x12(\n" +
	"\x05video\x18\x0e \x01(\v2\x10.ax.VideoContentH\x00R\x05video\x12=\n" +
	"\fconfirmation\x18\x1a \x01(\v2\x17.ax.ConfirmationContentH\x00R\fconfirmation\x122\n" +
	"\ttool_call\x18\x18 \x01(\v2\x13.ax.ToolCallContentH\x00R\btoolCall\x128\n" +
	"\vtool_result\x18\x19 \x01(\v2\x15.ax.ToolResultContentH\x00R\n" +
	"toolResultB\x06\n" +
	"\x04typeJ\x04\b\x01\x10\x05J\x04\b\x06\x10\n" +
	"J\x04\b\x0f\x10\x18*b\n" +
	"\x0fMediaResolution\x12 \n" +
	"\x1cMEDIA_RESOLUTION_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\x0e\n" +
	"\n" +
	"ULTRA_HIGH\x10\x04B\x1cZ\x1agithub.com/google/ax/protob\x06proto3"

var (
	file_proto_content_proto_rawDescOnce sync.Once
	file_proto_content_proto_rawDescData []byte
)

func file_proto_content_proto_rawDescGZIP() []byte {
	file_proto_content_proto_rawDescOnce.Do(func() {
		file_proto_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_content_proto_rawDesc), len(file_proto_content_proto_rawDesc)))
	})
	return file_proto_content_proto_rawDescData
}

var file_proto_content_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_content_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_content_proto_goTypes = []any{
	(MediaResolution)(0),          // 0: ax.MediaResolution
	(ImageContent_MimeType)(0),    // 1: ax.ImageContent.MimeType
	(AudioContent_MimeType)(0),    // 2: ax.AudioContent.MimeType
	(DocumentContent_MimeType)(0), // 3: ax.DocumentContent.MimeType
	(VideoContent_MimeType)(0),    // 4: ax.VideoContent.MimeType
	(*TextContent)(nil),           // 5: ax.TextContent
	(*ApprovalDecision)(nil),      // 6: ax.ApprovalDecision
	(*DeclineDecision)(nil),       // 7: ax.DeclineDecision
	(*ConfirmationContent)(nil),   // 8: ax.ConfirmationContent
	(*ThoughtSummaryContent)(nil), // 9: ax.ThoughtSummaryContent
	(*ThoughtContent)(nil),        // 10: ax.ThoughtContent
	(*ToolCallContent)(nil),       // 11: ax.ToolCallContent
	(*ToolResultContent)(nil),     // 12: ax.ToolResultContent
	(*FunctionCallContent)(nil),   // 13: ax.FunctionCallContent
	(*FunctionResultContent)(nil), // 14: ax.FunctionResultContent
	(*ImageContent)(nil),          // 15: ax.ImageContent
	(*AudioContent)(nil),          // 16: ax.AudioContent
	(*DocumentContent)(nil),       // 17: ax.DocumentContent
	(*VideoContent)(nil),          // 18: ax.VideoContent
	(*Content)(nil),               // 19: ax.Content
	(*structpb.Struct)(nil),       // 20: google.protobuf.Struct
}
var file_proto_content_proto_depIdxs = []int32{
	6,  // 0: ax.ConfirmationContent.approval:type_name -> ax.ApprovalDecision
	7,  // 1: ax.ConfirmationContent.decline:type_name -> ax.DeclineDecision
	5,  // 2: ax.ThoughtSummaryContent.text:type_name -> ax.TextContent
	9,  // 3: ax.ThoughtContent.summary:type_name -> ax.ThoughtSummaryContent
	13, // 4: ax.ToolCallContent.function_call:type_name -> ax.FunctionCallContent
	14, // 5: ax.ToolResultContent.function_result:type_name -> ax.FunctionResultContent
	20, // 6: ax.FunctionCallContent.arguments:type_name -> google.protobuf.Struct
	20, // 7: ax.FunctionResultContent.response:type_name -> google.protobuf.Struct
	1,  // 8: ax.ImageContent.mime_type:type_name -> ax.ImageContent.MimeType
	0,  // 9: ax.ImageContent.resolution:type_name -> ax.MediaResolution
	2,  // 10: ax.AudioContent.mime_type:type_name -> ax.AudioContent.MimeType
	3,  // 11: ax.DocumentContent.mime_type:type_name -> ax.DocumentContent.MimeType
	4,  // 12: ax.VideoContent.mime_type:type_name -> ax.VideoContent.MimeType
	0,  // 13: ax.VideoContent.resolution:type_name -> ax.MediaResolution
	10, // 14: ax.Content.thought:type_name -> ax.ThoughtContent
	5,  // 15: ax.Content.text:type_name -> ax.TextContent
	15, // 16: ax.Content.image:type_name -> ax.ImageContent
	16, // 17: ax.Content.audio:type_name -> ax.AudioContent
	17, // 18: ax.Content.document:type_name -> ax.DocumentContent
	18, // 19: ax.Content.video:type_name -> ax.VideoContent
	8,  // 20: ax.Content.confirmation:type_name -> ax.ConfirmationContent
	11, // 21: ax.Content.tool_call:type_name -> ax.ToolCallContent
	12, // 22: ax.Content.tool_result:type_name -> ax.ToolResultContent
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_proto_content_proto_init() }
func file_proto_content_proto_init() {
	if File_proto_content_proto != nil {
		return
	}
	file_proto_content_proto_msgTypes[3].OneofWrappers = []any{
		(*ConfirmationContent_Approval)(nil),
		(*ConfirmationContent_Decline)(nil),
	}
	file_proto_content_proto_msgTypes[4].OneofWrappers = []any{
		(*ThoughtSummaryContent_Text)(nil),
	}
	file_proto_content_proto_msgTypes[6].OneofWrappers = []any{
		(*ToolCallContent_FunctionCall)(nil),
	}
	file_proto_content_proto_msgTypes[7].OneofWrappers = []any{
		(*ToolResultContent_FunctionResult)(nil),
	}
	file_proto_content_proto_msgTypes[9].OneofWrappers = []any{
		(*FunctionResultContent_Response)(nil),
	}
	file_proto_content_proto_msgTypes[10].OneofWrappers = []any{
		(*ImageContent_Data)(nil),
		(*ImageContent_Uri)(nil),
	}
	file_proto_content_proto_msgTypes[11].OneofWrappers = []any{
		(*AudioContent_Data)(nil),
		(*AudioContent_Uri)(nil),
	}
	file_proto_content_proto_msgTypes[12].OneofWrappers = []any{
		(*DocumentContent_Data)(nil),
		(*DocumentContent_Uri)(nil),
	}
	file_proto_content_proto_msgTypes[13].OneofWrappers = []any{
		(*VideoContent_Data)(nil),
		(*VideoContent_Uri)(nil),
	}
	file_proto_content_proto_msgTypes[14].OneofWrappers = []any{
		(*Content_Thought)(nil),
		(*Content_Text)(nil),
		(*Content_Image)(nil),
		(*Content_Audio)(nil),
		(*Content_Document)(nil),
		(*Content_Video)(nil),
		(*Content_Confirmation)(nil),
		(*Content_ToolCall)(nil),
		(*Content_ToolResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_content_proto_rawDesc), len(file_proto_content_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_content_proto_goTypes,
		DependencyIndexes: file_proto_content_proto_depIdxs,
		EnumInfos:         file_proto_content_proto_enumTypes,
		MessageInfos:      file_proto_content_proto_msgTypes,
	}.Build()
	File_proto_content_proto = out.File
	file_proto_content_proto_goTypes = nil
	file_proto_content_proto_depIdxs = nil
}
