// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/gar.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State represents the state of a session
type State int32

const (
	State_STATE_UNSPECIFIED State = 0 // Unspecified state
	State_STATE_RUNNING     State = 1 // Session is currently running
	State_STATE_FAILED      State = 2 // Session failed
	State_STATE_COMPLETED   State = 3 // Completed, can accept new triggers
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_RUNNING",
		2: "STATE_FAILED",
		3: "STATE_COMPLETED",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_RUNNING":     1,
		"STATE_FAILED":      2,
		"STATE_COMPLETED":   3,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gar_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_proto_gar_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{0}
}

// ProcessRequest is an input to an agent.
type ProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Checkpoint is the optional checkpoint associated with
	// the contents.
	CheckpointId string `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	// Contents as input.
	Contents      []*Content `protobuf:"bytes,2,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_proto_gar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *ProcessRequest) GetContents() []*Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

// ProcessResponse is an output from an agent.
// It can be returned in a streaming fashion.
type ProcessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Checkpoint is the optional checkpoint associated with
	// the contents.
	CheckpointId string `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	// Contents as output.
	Contents []*Content `protobuf:"bytes,2,rep,name=contents,proto3" json:"contents,omitempty"`
	// Optional agent handoff. If set controller, hands off the
	// execution to the provided agent.
	AgentHandoff  string `protobuf:"bytes,3,opt,name=agent_handoff,json=agentHandoff,proto3" json:"agent_handoff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_proto_gar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessResponse) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *ProcessResponse) GetContents() []*Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *ProcessResponse) GetAgentHandoff() string {
	if x != nil {
		return x.AgentHandoff
	}
	return ""
}

// TextContent represents a text content.
type TextContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextContent) Reset() {
	*x = TextContent{}
	mi := &file_proto_gar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextContent) ProtoMessage() {}

func (x *TextContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextContent.ProtoReflect.Descriptor instead.
func (*TextContent) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{2}
}

func (x *TextContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Content represents a message with role, type, mimetype, and data fields
type Content struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*Content_Text
	Content       isContent_Content `protobuf_oneof:"content"`
	Role          string            `protobuf:"bytes,1000,opt,name=role,proto3" json:"role,omitempty"` // The role of the content (e.g., "user", "assistant", "system")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_proto_gar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{3}
}

func (x *Content) GetContent() isContent_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Content) GetText() *TextContent {
	if x != nil {
		if x, ok := x.Content.(*Content_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *Content) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type isContent_Content interface {
	isContent_Content()
}

type Content_Text struct {
	Text *TextContent `protobuf:"bytes,10,opt,name=text,proto3,oneof"`
}

func (*Content_Text) isContent_Content() {}

// Event that represents a session state change.
// Some sessions may not be resumable based on their latest state.
// For example, controller doesn't continue a session once
// the state is set to STATE_FAILED.
type SessionStateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         State                  `protobuf:"varint,1,opt,name=state,proto3,enum=proto.State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStateEvent) Reset() {
	*x = SessionStateEvent{}
	mi := &file_proto_gar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStateEvent) ProtoMessage() {}

func (x *SessionStateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStateEvent.ProtoReflect.Descriptor instead.
func (*SessionStateEvent) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{4}
}

func (x *SessionStateEvent) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

// AgentCallEvent represents an agent call.
type AgentCallEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Contents      []*Content             `protobuf:"bytes,4,rep,name=contents,proto3" json:"contents,omitempty"`
	AwaitingMore  bool                   `protobuf:"varint,5,opt,name=awaiting_more,json=awaitingMore,proto3" json:"awaiting_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCallEvent) Reset() {
	*x = AgentCallEvent{}
	mi := &file_proto_gar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCallEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCallEvent) ProtoMessage() {}

func (x *AgentCallEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCallEvent.ProtoReflect.Descriptor instead.
func (*AgentCallEvent) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{5}
}

func (x *AgentCallEvent) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *AgentCallEvent) GetContents() []*Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *AgentCallEvent) GetAwaitingMore() bool {
	if x != nil {
		return x.AwaitingMore
	}
	return false
}

// HandoffEvent represents an agent handoff.
// Controller records the agent handoff with
// associated content.
type HandoffEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceAgentId string                 `protobuf:"bytes,3,opt,name=source_agent_id,json=sourceAgentId,proto3" json:"source_agent_id,omitempty"`
	TargetAgentId string                 `protobuf:"bytes,4,opt,name=target_agent_id,json=targetAgentId,proto3" json:"target_agent_id,omitempty"`
	Contents      []*Content             `protobuf:"bytes,5,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandoffEvent) Reset() {
	*x = HandoffEvent{}
	mi := &file_proto_gar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandoffEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandoffEvent) ProtoMessage() {}

func (x *HandoffEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandoffEvent.ProtoReflect.Descriptor instead.
func (*HandoffEvent) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{6}
}

func (x *HandoffEvent) GetSourceAgentId() string {
	if x != nil {
		return x.SourceAgentId
	}
	return ""
}

func (x *HandoffEvent) GetTargetAgentId() string {
	if x != nil {
		return x.TargetAgentId
	}
	return ""
}

func (x *HandoffEvent) GetContents() []*Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

// Content changes such as user inputs are recorded
// as content events.
type ContentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      []*Content             `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentEvent) Reset() {
	*x = ContentEvent{}
	mi := &file_proto_gar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentEvent) ProtoMessage() {}

func (x *ContentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentEvent.ProtoReflect.Descriptor instead.
func (*ContentEvent) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{7}
}

func (x *ContentEvent) GetContents() []*Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

// Event is the entry in the event log. Events are used
// to record the actions taken place in the GAR controller.
// GAR controller can replay the events for resumability.
type Event struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SessionId           string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CheckpointId        string                 `protobuf:"bytes,2,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	SenderName          string                 `protobuf:"bytes,3,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	SenderId            string                 `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Timestamp           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ControllerTimestamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=controller_timestamp,json=controllerTimestamp,proto3" json:"controller_timestamp,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Event_SessionStateEvent
	//	*Event_AgentCallEvent
	//	*Event_HandoffEvent
	//	*Event_ContentEvent
	Kind          isEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_gar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{8}
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *Event) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *Event) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetControllerTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ControllerTimestamp
	}
	return nil
}

func (x *Event) GetKind() isEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Event) GetSessionStateEvent() *SessionStateEvent {
	if x != nil {
		if x, ok := x.Kind.(*Event_SessionStateEvent); ok {
			return x.SessionStateEvent
		}
	}
	return nil
}

func (x *Event) GetAgentCallEvent() *AgentCallEvent {
	if x != nil {
		if x, ok := x.Kind.(*Event_AgentCallEvent); ok {
			return x.AgentCallEvent
		}
	}
	return nil
}

func (x *Event) GetHandoffEvent() *HandoffEvent {
	if x != nil {
		if x, ok := x.Kind.(*Event_HandoffEvent); ok {
			return x.HandoffEvent
		}
	}
	return nil
}

func (x *Event) GetContentEvent() *ContentEvent {
	if x != nil {
		if x, ok := x.Kind.(*Event_ContentEvent); ok {
			return x.ContentEvent
		}
	}
	return nil
}

type isEvent_Kind interface {
	isEvent_Kind()
}

type Event_SessionStateEvent struct {
	SessionStateEvent *SessionStateEvent `protobuf:"bytes,7,opt,name=session_state_event,json=sessionStateEvent,proto3,oneof"`
}

type Event_AgentCallEvent struct {
	AgentCallEvent *AgentCallEvent `protobuf:"bytes,8,opt,name=agent_call_event,json=agentCallEvent,proto3,oneof"`
}

type Event_HandoffEvent struct {
	HandoffEvent *HandoffEvent `protobuf:"bytes,9,opt,name=handoff_event,json=handoffEvent,proto3,oneof"`
}

type Event_ContentEvent struct {
	ContentEvent *ContentEvent `protobuf:"bytes,10,opt,name=content_event,json=contentEvent,proto3,oneof"`
}

func (*Event_SessionStateEvent) isEvent_Kind() {}

func (*Event_AgentCallEvent) isEvent_Kind() {}

func (*Event_HandoffEvent) isEvent_Kind() {}

func (*Event_ContentEvent) isEvent_Kind() {}

// HealthCheckRequest for agent health checks
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_gar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{9}
}

// HealthCheckResponse contains agent health status
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_gar_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TriggerSessionRequest for triggering a new session
type TriggerSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`          // Unique session identifier
	CheckpointId  string                 `protobuf:"bytes,2,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"` // Optional: Resume from specific checkpoint UUID (empty for latest)
	Inputs        []*Content             `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`                                 // Input content to process
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSessionRequest) Reset() {
	*x = TriggerSessionRequest{}
	mi := &file_proto_gar_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSessionRequest) ProtoMessage() {}

func (x *TriggerSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSessionRequest.ProtoReflect.Descriptor instead.
func (*TriggerSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{11}
}

func (x *TriggerSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TriggerSessionRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *TriggerSessionRequest) GetInputs() []*Content {
	if x != nil {
		return x.Inputs
	}
	return nil
}

// TriggerSessionResponse contains the result of triggering a session
type TriggerSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`          // Session ID (in case it was generated or modified by server)
	CheckpointId  string                 `protobuf:"bytes,2,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"` // Current checkpoint ID
	Outputs       []*Content             `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`                               // Output content
	State         State                  `protobuf:"varint,4,opt,name=state,proto3,enum=proto.State" json:"state,omitempty"`                 // Session state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSessionResponse) Reset() {
	*x = TriggerSessionResponse{}
	mi := &file_proto_gar_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSessionResponse) ProtoMessage() {}

func (x *TriggerSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSessionResponse.ProtoReflect.Descriptor instead.
func (*TriggerSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{12}
}

func (x *TriggerSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TriggerSessionResponse) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *TriggerSessionResponse) GetOutputs() []*Content {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *TriggerSessionResponse) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

// GetSessionRequest for retrieving session details.
type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_proto_gar_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{13}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// SessionInfo contains session details.
type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         State                  `protobuf:"varint,1,opt,name=state,proto3,enum=proto.State" json:"state,omitempty"`
	ActiveAgents  []string               `protobuf:"bytes,2,rep,name=active_agents,json=activeAgents,proto3" json:"active_agents,omitempty"`
	CheckpointIds []string               `protobuf:"bytes,3,rep,name=checkpoint_ids,json=checkpointIds,proto3" json:"checkpoint_ids,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Session creation time
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Last update time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_proto_gar_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{14}
}

func (x *SessionInfo) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *SessionInfo) GetActiveAgents() []string {
	if x != nil {
		return x.ActiveAgents
	}
	return nil
}

func (x *SessionInfo) GetCheckpointIds() []string {
	if x != nil {
		return x.CheckpointIds
	}
	return nil
}

func (x *SessionInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SessionInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// GetSessionResponse contains session information.
type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionInfo           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_proto_gar_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{15}
}

func (x *GetSessionResponse) GetSession() *SessionInfo {
	if x != nil {
		return x.Session
	}
	return nil
}

type ForkSessionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SourceSessionId    string                 `protobuf:"bytes,1,opt,name=source_session_id,json=sourceSessionId,proto3" json:"source_session_id,omitempty"`
	SourceCheckpointId string                 `protobuf:"bytes,2,opt,name=source_checkpoint_id,json=sourceCheckpointId,proto3" json:"source_checkpoint_id,omitempty"` // Checkpoint ID within the source session to fork from.
	DestSessionId      string                 `protobuf:"bytes,3,opt,name=dest_session_id,json=destSessionId,proto3" json:"dest_session_id,omitempty"`                // New session ID. If provided, must not exist.
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ForkSessionRequest) Reset() {
	*x = ForkSessionRequest{}
	mi := &file_proto_gar_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkSessionRequest) ProtoMessage() {}

func (x *ForkSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkSessionRequest.ProtoReflect.Descriptor instead.
func (*ForkSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{16}
}

func (x *ForkSessionRequest) GetSourceSessionId() string {
	if x != nil {
		return x.SourceSessionId
	}
	return ""
}

func (x *ForkSessionRequest) GetSourceCheckpointId() string {
	if x != nil {
		return x.SourceCheckpointId
	}
	return ""
}

func (x *ForkSessionRequest) GetDestSessionId() string {
	if x != nil {
		return x.DestSessionId
	}
	return ""
}

type ForkSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewSessionId  string                 `protobuf:"bytes,1,opt,name=new_session_id,json=newSessionId,proto3" json:"new_session_id,omitempty"` // New session ID (in case it was generated or modified by server)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForkSessionResponse) Reset() {
	*x = ForkSessionResponse{}
	mi := &file_proto_gar_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkSessionResponse) ProtoMessage() {}

func (x *ForkSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkSessionResponse.ProtoReflect.Descriptor instead.
func (*ForkSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{17}
}

func (x *ForkSessionResponse) GetNewSessionId() string {
	if x != nil {
		return x.NewSessionId
	}
	return ""
}

// RegisterAgentRequest for registering an agent
type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // Human-readable name for the agent
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // Description of agent capabilities
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`         // gRPC address for remote agents
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_proto_gar_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{18}
}

func (x *RegisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterAgentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterAgentRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterAgentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// RegisterAgentResponse contains registration result
type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_proto_gar_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{19}
}

// UnregisterAgentRequest for unregistering an agent
type UnregisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterAgentRequest) Reset() {
	*x = UnregisterAgentRequest{}
	mi := &file_proto_gar_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAgentRequest) ProtoMessage() {}

func (x *UnregisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAgentRequest.ProtoReflect.Descriptor instead.
func (*UnregisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{20}
}

func (x *UnregisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// UnregisterAgentResponse contains unregistration result
type UnregisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterAgentResponse) Reset() {
	*x = UnregisterAgentResponse{}
	mi := &file_proto_gar_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAgentResponse) ProtoMessage() {}

func (x *UnregisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gar_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAgentResponse.ProtoReflect.Descriptor instead.
func (*UnregisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_gar_proto_rawDescGZIP(), []int{21}
}

var File_proto_gar_proto protoreflect.FileDescriptor

const file_proto_gar_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/gar.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"a\n" +
	"\x0eProcessRequest\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12*\n" +
	"\bcontents\x18\x02 \x03(\v2\x0e.proto.ContentR\bcontents\"\x87\x01\n" +
	"\x0fProcessResponse\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12*\n" +
	"\bcontents\x18\x02 \x03(\v2\x0e.proto.ContentR\bcontents\x12#\n" +
	"\ragent_handoff\x18\x03 \x01(\tR\fagentHandoff\"3\n" +
	"\vTextContent\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04textJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03R\x04type\"e\n" +
	"\aContent\x12(\n" +
	"\x04text\x18\n" +
	" \x01(\v2\x12.proto.TextContentH\x00R\x04text\x12\x13\n" +
	"\x04role\x18\xe8\a \x01(\tR\x04roleB\t\n" +
	"\acontentJ\x04\b\x01\x10\x05J\x04\b\x06\x10\n" +
	"J\x04\b\v\x10\x1a\"7\n" +
	"\x11SessionStateEvent\x12\"\n" +
	"\x05state\x18\x01 \x01(\x0e2\f.proto.StateR\x05state\"\x85\x01\n" +
	"\x0eAgentCallEvent\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12*\n" +
	"\bcontents\x18\x04 \x03(\v2\x0e.proto.ContentR\bcontents\x12#\n" +
	"\rawaiting_more\x18\x05 \x01(\bR\fawaitingMoreJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03\"\x96\x01\n" +
	"\fHandoffEvent\x12&\n" +
	"\x0fsource_agent_id\x18\x03 \x01(\tR\rsourceAgentId\x12&\n" +
	"\x0ftarget_agent_id\x18\x04 \x01(\tR\rtargetAgentId\x12*\n" +
	"\bcontents\x18\x05 \x03(\v2\x0e.proto.ContentR\bcontentsJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03\":\n" +
	"\fContentEvent\x12*\n" +
	"\bcontents\x18\x01 \x03(\v2\x0e.proto.ContentR\bcontents\"\xa1\x04\n" +
	"\x05Event\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rcheckpoint_id\x18\x02 \x01(\tR\fcheckpointId\x12\x1f\n" +
	"\vsender_name\x18\x03 \x01(\tR\n" +
	"senderName\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\tR\bsenderId\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12M\n" +
	"\x14controller_timestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x13controllerTimestamp\x12J\n" +
	"\x13session_state_event\x18\a \x01(\v2\x18.proto.SessionStateEventH\x00R\x11sessionStateEvent\x12A\n" +
	"\x10agent_call_event\x18\b \x01(\v2\x15.proto.AgentCallEventH\x00R\x0eagentCallEvent\x12:\n" +
	"\rhandoff_event\x18\t \x01(\v2\x13.proto.HandoffEventH\x00R\fhandoffEvent\x12:\n" +
	"\rcontent_event\x18\n" +
	" \x01(\v2\x13.proto.ContentEventH\x00R\fcontentEventB\x06\n" +
	"\x04kind\"\x14\n" +
	"\x12HealthCheckRequest\"I\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x83\x01\n" +
	"\x15TriggerSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rcheckpoint_id\x18\x02 \x01(\tR\fcheckpointId\x12&\n" +
	"\x06inputs\x18\x03 \x03(\v2\x0e.proto.ContentR\x06inputs\"\xaa\x01\n" +
	"\x16TriggerSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rcheckpoint_id\x18\x02 \x01(\tR\fcheckpointId\x12(\n" +
	"\aoutputs\x18\x03 \x03(\v2\x0e.proto.ContentR\aoutputs\x12\"\n" +
	"\x05state\x18\x04 \x01(\x0e2\f.proto.StateR\x05state\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xf3\x01\n" +
	"\vSessionInfo\x12\"\n" +
	"\x05state\x18\x01 \x01(\x0e2\f.proto.StateR\x05state\x12#\n" +
	"\ractive_agents\x18\x02 \x03(\tR\factiveAgents\x12%\n" +
	"\x0echeckpoint_ids\x18\x03 \x03(\tR\rcheckpointIds\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"B\n" +
	"\x12GetSessionResponse\x12,\n" +
	"\asession\x18\x01 \x01(\v2\x12.proto.SessionInfoR\asession\"\x9a\x01\n" +
	"\x12ForkSessionRequest\x12*\n" +
	"\x11source_session_id\x18\x01 \x01(\tR\x0fsourceSessionId\x120\n" +
	"\x14source_checkpoint_id\x18\x02 \x01(\tR\x12sourceCheckpointId\x12&\n" +
	"\x0fdest_session_id\x18\x03 \x01(\tR\rdestSessionId\";\n" +
	"\x13ForkSessionResponse\x12$\n" +
	"\x0enew_session_id\x18\x01 \x01(\tR\fnewSessionId\"\x85\x02\n" +
	"\x14RegisterAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12E\n" +
	"\bmetadata\x18\x05 \x03(\v2).proto.RegisterAgentRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x17\n" +
	"\x15RegisterAgentResponse\"3\n" +
	"\x16UnregisterAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x19\n" +
	"\x17UnregisterAgentResponse*X\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATE_RUNNING\x10\x01\x12\x10\n" +
	"\fSTATE_FAILED\x10\x02\x12\x13\n" +
	"\x0fSTATE_COMPLETED\x10\x032\x92\x01\n" +
	"\fAgentService\x12<\n" +
	"\aProcess\x12\x15.proto.ProcessRequest\x1a\x16.proto.ProcessResponse(\x010\x01\x12D\n" +
	"\vHealthCheck\x12\x19.proto.HealthCheckRequest\x1a\x1a.proto.HealthCheckResponse2\x84\x03\n" +
	"\n" +
	"GARService\x12O\n" +
	"\x0eTriggerSession\x12\x1c.proto.TriggerSessionRequest\x1a\x1d.proto.TriggerSessionResponse0\x01\x12A\n" +
	"\n" +
	"GetSession\x12\x18.proto.GetSessionRequest\x1a\x19.proto.GetSessionResponse\x12D\n" +
	"\vForkSession\x12\x19.proto.ForkSessionRequest\x1a\x1a.proto.ForkSessionResponse\x12J\n" +
	"\rRegisterAgent\x12\x1b.proto.RegisterAgentRequest\x1a\x1c.proto.RegisterAgentResponse\x12P\n" +
	"\x0fUnregisterAgent\x12\x1d.proto.UnregisterAgentRequest\x1a\x1e.proto.UnregisterAgentResponseB\x1dZ\x1bgithub.com/google/gar/protob\x06proto3"

var (
	file_proto_gar_proto_rawDescOnce sync.Once
	file_proto_gar_proto_rawDescData []byte
)

func file_proto_gar_proto_rawDescGZIP() []byte {
	file_proto_gar_proto_rawDescOnce.Do(func() {
		file_proto_gar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gar_proto_rawDesc), len(file_proto_gar_proto_rawDesc)))
	})
	return file_proto_gar_proto_rawDescData
}

var file_proto_gar_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_gar_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_gar_proto_goTypes = []any{
	(State)(0),                      // 0: proto.State
	(*ProcessRequest)(nil),          // 1: proto.ProcessRequest
	(*ProcessResponse)(nil),         // 2: proto.ProcessResponse
	(*TextContent)(nil),             // 3: proto.TextContent
	(*Content)(nil),                 // 4: proto.Content
	(*SessionStateEvent)(nil),       // 5: proto.SessionStateEvent
	(*AgentCallEvent)(nil),          // 6: proto.AgentCallEvent
	(*HandoffEvent)(nil),            // 7: proto.HandoffEvent
	(*ContentEvent)(nil),            // 8: proto.ContentEvent
	(*Event)(nil),                   // 9: proto.Event
	(*HealthCheckRequest)(nil),      // 10: proto.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 11: proto.HealthCheckResponse
	(*TriggerSessionRequest)(nil),   // 12: proto.TriggerSessionRequest
	(*TriggerSessionResponse)(nil),  // 13: proto.TriggerSessionResponse
	(*GetSessionRequest)(nil),       // 14: proto.GetSessionRequest
	(*SessionInfo)(nil),             // 15: proto.SessionInfo
	(*GetSessionResponse)(nil),      // 16: proto.GetSessionResponse
	(*ForkSessionRequest)(nil),      // 17: proto.ForkSessionRequest
	(*ForkSessionResponse)(nil),     // 18: proto.ForkSessionResponse
	(*RegisterAgentRequest)(nil),    // 19: proto.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),   // 20: proto.RegisterAgentResponse
	(*UnregisterAgentRequest)(nil),  // 21: proto.UnregisterAgentRequest
	(*UnregisterAgentResponse)(nil), // 22: proto.UnregisterAgentResponse
	nil,                             // 23: proto.RegisterAgentRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),   // 24: google.protobuf.Timestamp
}
var file_proto_gar_proto_depIdxs = []int32{
	4,  // 0: proto.ProcessRequest.contents:type_name -> proto.Content
	4,  // 1: proto.ProcessResponse.contents:type_name -> proto.Content
	3,  // 2: proto.Content.text:type_name -> proto.TextContent
	0,  // 3: proto.SessionStateEvent.state:type_name -> proto.State
	4,  // 4: proto.AgentCallEvent.contents:type_name -> proto.Content
	4,  // 5: proto.HandoffEvent.contents:type_name -> proto.Content
	4,  // 6: proto.ContentEvent.contents:type_name -> proto.Content
	24, // 7: proto.Event.timestamp:type_name -> google.protobuf.Timestamp
	24, // 8: proto.Event.controller_timestamp:type_name -> google.protobuf.Timestamp
	5,  // 9: proto.Event.session_state_event:type_name -> proto.SessionStateEvent
	6,  // 10: proto.Event.agent_call_event:type_name -> proto.AgentCallEvent
	7,  // 11: proto.Event.handoff_event:type_name -> proto.HandoffEvent
	8,  // 12: proto.Event.content_event:type_name -> proto.ContentEvent
	4,  // 13: proto.TriggerSessionRequest.inputs:type_name -> proto.Content
	4,  // 14: proto.TriggerSessionResponse.outputs:type_name -> proto.Content
	0,  // 15: proto.TriggerSessionResponse.state:type_name -> proto.State
	0,  // 16: proto.SessionInfo.state:type_name -> proto.State
	24, // 17: proto.SessionInfo.created_at:type_name -> google.protobuf.Timestamp
	24, // 18: proto.SessionInfo.updated_at:type_name -> google.protobuf.Timestamp
	15, // 19: proto.GetSessionResponse.session:type_name -> proto.SessionInfo
	23, // 20: proto.RegisterAgentRequest.metadata:type_name -> proto.RegisterAgentRequest.MetadataEntry
	1,  // 21: proto.AgentService.Process:input_type -> proto.ProcessRequest
	10, // 22: proto.AgentService.HealthCheck:input_type -> proto.HealthCheckRequest
	12, // 23: proto.GARService.TriggerSession:input_type -> proto.TriggerSessionRequest
	14, // 24: proto.GARService.GetSession:input_type -> proto.GetSessionRequest
	17, // 25: proto.GARService.ForkSession:input_type -> proto.ForkSessionRequest
	19, // 26: proto.GARService.RegisterAgent:input_type -> proto.RegisterAgentRequest
	21, // 27: proto.GARService.UnregisterAgent:input_type -> proto.UnregisterAgentRequest
	2,  // 28: proto.AgentService.Process:output_type -> proto.ProcessResponse
	11, // 29: proto.AgentService.HealthCheck:output_type -> proto.HealthCheckResponse
	13, // 30: proto.GARService.TriggerSession:output_type -> proto.TriggerSessionResponse
	16, // 31: proto.GARService.GetSession:output_type -> proto.GetSessionResponse
	18, // 32: proto.GARService.ForkSession:output_type -> proto.ForkSessionResponse
	20, // 33: proto.GARService.RegisterAgent:output_type -> proto.RegisterAgentResponse
	22, // 34: proto.GARService.UnregisterAgent:output_type -> proto.UnregisterAgentResponse
	28, // [28:35] is the sub-list for method output_type
	21, // [21:28] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_proto_gar_proto_init() }
func file_proto_gar_proto_init() {
	if File_proto_gar_proto != nil {
		return
	}
	file_proto_gar_proto_msgTypes[3].OneofWrappers = []any{
		(*Content_Text)(nil),
	}
	file_proto_gar_proto_msgTypes[8].OneofWrappers = []any{
		(*Event_SessionStateEvent)(nil),
		(*Event_AgentCallEvent)(nil),
		(*Event_HandoffEvent)(nil),
		(*Event_ContentEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gar_proto_rawDesc), len(file_proto_gar_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_gar_proto_goTypes,
		DependencyIndexes: file_proto_gar_proto_depIdxs,
		EnumInfos:         file_proto_gar_proto_enumTypes,
		MessageInfos:      file_proto_gar_proto_msgTypes,
	}.Build()
	File_proto_gar_proto = out.File
	file_proto_gar_proto_goTypes = nil
	file_proto_gar_proto_depIdxs = nil
}
